site_name: ROAR Documentation
site_description: Robot Open Autonomous Racing is a platform/competition dedicated to teaching students to gain a holistic view and hands-on(virtual) experiences about building a high-performance fully-autonomous 1/10 scale RC car from scratch.
nav:
    - About:
      - Introduction: introduction.md
      - Architecture: architecture.md
      - Coordinate: coordinate.md
    - Quick Start: quickstart.md
        - ROAR Simulation:
            - Carla Client:
                - Carla Runner: code_documentations/ROAR_Sim/carla_client.md
                - Util:
                    - Camera Manager: code_documentations/ROAR_Sim/camera.md
                    - Hud: code_documentations/ROAR_Sim/hud.md
                    - Keyboard Controls: code_documentations/ROAR_Sim/kbc.md
                    - Sensors: code_documentations/ROAR_Sim/sensors.md
                    - Utilities: code_documentations/ROAR_Sim/util.md
                    - World: code_documentations/ROAR_Sim/world.md
            - Configurations: code_documentations/ROAR_Sim/conf.md
        - Runner Sim: code_documentations/runner_sim.md
    - Competition Instruction: competition_instruction.md
    - FAQ: faq.md


markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.emoji
  - pymdownx.tabbed
  - toc:
      permalink: "¤"


theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          rendering:
            show_root_heading: no
            show_category_heading: false
            show_if_no_docstring: yes
            show_source: true
            show_root_toc_entry: false
            show_object_full_path: no

